### ISSUE TITLE
Enable tab-based completion candidate selection in Bash

### ISSUE THREAD

**Issue by elim** [elim/dotfiles#104]
## User Story

**As a** user of Bash,  
**I want** to display and select completion candidates by pressing the tab key,  
**because** I sometimes have to use Bash, and I want to have a more comfortable experience when doing so.

## Acceptance Criteria

Completion candidates should be displayed and selectable by pressing the tab key when using Bash.

## Tasks

- [ ] Ensure `~/.inputrc` is managed by home-manager.
- [ ] Enable `menu-complete` in `~/.inputrc`.
- [ ] Enable `show-all-if-ambiguous` in `~/.inputrc`.
