### ISSUE TITLE
Full Management of my dotfiles with Home Manager

### ISSUE THREAD

**Issue by elim** [elim/dotfiles#105]
## User Story

As a Nix wannabe, I want to manage my entire dotfiles setup exclusively with Home Manager, because my current system relies on both custom deployment scripts and Home Manager, leading to confusion about what manages what, and requiring both systems to be executed in the correct order to properly set up my environment.

## Acceptance Criteria

- All my dotfiles are managed solely through Home Manager.
  - Existing configuration migration to Home Manager will be handled separately, but for now, symlinks or other shortcuts may be used.
  - Even in cases where symlinks are used, they must be generated via Nix.

## Tasks

- [x] Adapt the current dotfiles deployment to be handled by Home Manager.
- [x] Remove the current deployment scripts.
- [ ] (Optional) Create a README to document the setup process briefly.

**Comment by elim** [comment]
> * [x]  Adapt the current dotfiles deployment to be handled by Home Manager.
> * [x]  Remove the current deployment scripts.

They were completed by 3d5b5cb1fd0676ed2e752f4b68539d662850ae65.
